version: "3"

services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - RAZZLE_APP_NAME=globalsearch

      - PROXY_ELASTIC_HOST=
      - PROXY_ELASTIC_PORT=
      - PROXY_ELASTIC_USER=
      - PROXY_ELASTIC_PWD=
      - PROXY_ELASTIC_INDEX=global-search_prod

      - RAZZLE_ES_PROXY_ADDR=http://localhost:3000

    # entrypoint: sh -c "tail -f /dev/null"
