packages:
  - 'packages/searchlib'
  - 'packages/searchlib-middleware'
  - 'packages/searchlib-less'
  - 'packages/searchlib-standalone'
  - 'packages/demo'
  - 'packages/wise'
link-workspace-packages: true
prefer-workspace-packages: true
