# Local development volumes
#---
version: '2.1'
x-airflow-override:
  &airflow-override
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./logs:/opt/airflow/logs

services:
  redis:
    # ports:
    #   - 6379:6379

  airflow-webserver:
    ports:
      - "8100:8080"
    <<: *airflow-override

  airflow-scheduler:
    <<: *airflow-override

  airflow-worker:
    <<: *airflow-override

  airflow-init:
    <<: *airflow-override

  flower:
    <<: *airflow-override
    ports:
      - "5555:5555"

  es:
    ports:
      - 9200:9200

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  logstash:
    ports:
      - 9600:9600

  # postgrest:
  #   ports:
  #     - "6000:3000"
  #
  # postgres-db:
  #   ports:
  #     - "5432:5432"
  # swagger:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - "8081:8080"
  #   expose:
  #     - "8081"
  #   environment:
  #     API_URL: http://localhost:3000/
