version: "2"

services:
  airflow-webserver:
    build: ./eea.docker.airflow
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '["https://biodiversity.europa.eu"]'
      SENTRY_DSN: ''
      DEV_ENV: "true"

    volumes:
      - ./eea-crawler/dags:/opt/airflow/dags
  airflow-scheduler:
    build: ./eea.docker.airflow
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '["https://biodiversity.europa.eu"]'
      SENTRY_DSN: ''
      DEV_ENV: "true"

    volumes:
      - ./eea-crawler/dags:/opt/airflow/dags

  airflow-worker:
    build: ./eea.docker.airflow
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '["https://biodiversity.europa.eu"]'
      SENTRY_DSN: ''
      DEV_ENV: "true"
    volumes:
      - ./eea-crawler/dags:/opt/airflow/dags

  airflow-init:
    build: ./eea.docker.airflow
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '["https://biodiversity.europa.eu"]'
      SENTRY_DSN: ''
      DEV_ENV: "true"
    volumes:
      - ./eea-crawler/dags:/opt/airflow/dags

  flower:
    build: ./eea.docker.airflow
    environment:
      AIRFLOW_VAR_INDEXED_WEBSITES: '["https://biodiversity.europa.eu"]'
      SENTRY_DSN: ''
      DEV_ENV: "true"
    volumes:
      - ./eea-crawler/dags:/opt/airflow/dags

  logstash:
    build: ./eea.docker.logstash
    environment:
      DEV_ENV: "true"

    volumes:
      - ./eea-crawler/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./eea-crawler/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
 